apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml
    kompose.version: 1.26.1 (a9d05d509)
  creationTimestamp: null
  labels:
    io.kompose.service: result
  name: result
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: result
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose.yml
        kompose.version: 1.26.1 (a9d05d509)
      creationTimestamp: null
      labels:
        io.kompose.network/mynetwork: "true"
        io.kompose.service: result
    spec:
      containers:
        - env:
            - name: POSTGRES_HOST
              value: postgresdb
          image: result
          livenessProbe:
            exec:
              command:
                - curl
                - -f
                - http://localhost:3000/
            failureThreshold: 3
            periodSeconds: 10
            timeoutSeconds: 5
          name: result
          ports:
            - containerPort: 3000
          resources: {}
      restartPolicy: Always
status: {}
