apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml
    kompose.version: 1.26.1 (a9d05d509)
  creationTimestamp: null
  labels:
    io.kompose.service: vote
  name: vote
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: vote
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose.yml
        kompose.version: 1.26.1 (a9d05d509)
      creationTimestamp: null
      labels:
        io.kompose.network/mynetwork: "true"
        io.kompose.service: vote
    spec:
      containers:
        - env:
            - name: REDIS_HOST
              value: redis
          image: vote
          name: vote
          ports:
            - containerPort: 8501
          resources: {}
      restartPolicy: Always
status: {}
